### ISSUE TITLE
Weird layout of some clan chat messages

### ISSUE THREAD

**Issue by xtomyserrax** [RoinujNosde/SimpleClans#102] opened 2020-11-30 03:45 UTC
I sometimes have this weird layout and I dont know why. Basicly I have this weird enter (Im using version 2.14.2)

![image](https://user-images.githubusercontent.com/6054192/100566669-67f47a00-32a5-11eb-9f77-a33fd3371534.png)

**Comment by SrBedrock** [comment] 2020-11-30 03:49
I believe it happens in other system messages as well.
https://github.com/RoinujNosde/SimpleClans/issues/19#issuecomment-672853636

**Comment by RoinujNosde** [comment] 2020-11-30 10:17
@xtomyserrax were there enough space for "economia" after "tener"?

**Comment by xtomyserrax** [comment] 2020-11-30 12:44
Nope, message was: "por si quieren tener economia propia del cla", no extra spaces

**Comment by RoinujNosde** [comment] 2020-11-30 12:56
I mean, would the word "economia" fit after "tener"? Considering your chat width.
It seems that the first line break is from Minecraft and the second from SimpleClans.

**Comment by xtomyserrax** [comment] 2020-11-30 13:10
Oh got you, yeah, economia is placed correctly, the problem here is the extra enter of propia del cla

**Comment by RoinujNosde** [comment] 2020-11-30 13:15
Duplicate of #19

**Closed as completed by RoinujNosde** 2020-11-30 13:15 UTC
Labels: bug
