### ISSUE TITLE
Better Control Over Clan Member Count Limits

### ISSUE THREAD

**Issue by Amirali1059** [RoinujNosde/SimpleClans#421] opened 2024-02-28 20:39 UTC
**Is your feature request related to a problem? Please describe.**
I wanted to configure some smart clan member count limits but realized the plugin only supports a constant number for clan member limits after searching through the documentation.

**Describe the solution you'd like**
It would be nice to have a feature where a permission could be used to set clan member limits when given to the clan leader.

**Describe alternatives you've considered**
If the above idea is not considered, it would be useful to have the ability to set different member count limits for _verified_ clans versus _unverified_ clans.

**Additional context**
Having this feature could encourage clan leaders to verify their clans to gain the ability to invite more players to their clan.

**Comment by Nishikiyama** [comment] 2024-02-28 21:05
Personally, I think it's a great idea

However I do think letting clan leaders set their own member limits is kind of on the verge of conventional or inconventional.

**Comment by RoinujNosde** [comment] 2024-02-28 21:12
Possible duplicate of #208

**Comment by Nishikiyama** [comment] 2024-02-28 21:18
> Possible duplicate of #208

Half-dupe
Changing members via config for two different clan member values (Verified / Non-verified...) 
versus
Changing clan member limit via unlockables

Personally, I think not a dupe, since both can be made, for example non-verified clans get x amount of max members , verified could be **first** upgrade for all upgrades to come, and verifying clan opens up in-game purchase menu which after that you could buy **more** members

**Comment by Amirali1059** [comment] 2024-02-29 12:04
> However I do think letting clan leaders set their own member limits is kind of on the verge of conventional or inconventional.

Thank you for your time!

I was thinking of the _permission_ feature more like an _admin_ option, so you can change how many members can be in someone's clan based on their _play time_ on the server, or _their rank_, or based on how much _money_ they have in their clan bank.

**Comment by Nishikiyama** [comment] 2024-02-29 14:17
> so you can change how many members can be in someone's clan based on their _play time_ on the server, or _their rank_, or based on how much _money_ they have in their clan bank.

So more like a command then instead of automation?

**Comment by Amirali1059** [comment] 2024-03-06 11:00
> > so you can change how many members can be in someone's clan based on their _play time_ on the server, or _their rank_, or based on how much _money_ they have in their clan bank.
> 
> So more like a command then instead of automation?

Kind of, #422 is fine, thank you for considering it! sorry for no reply in a long time.

**Comment by Nishikiyama** [comment] 2024-03-06 12:09
> > > so you can change how many members can be in someone's clan based on their _play time_ on the server, or _their rank_, or based on how much _money_ they have in their clan bank.
> > 
> > 
> > So more like a command then instead of automation?
> 
> Kind of, #422 is fine, thank you for considering it! sorry for no reply in a long time.

I think the way I made it is just fine, of course a more advanced version of it can be made but I believe for now that is quite enough :)

Of course I'm open to suggestions?

**Comment by Amirali1059** [comment] 2024-03-19 09:30
Thank you for your time, I think I close the issue as the feature is implemented now.

**Closed as completed** 2024-03-19 09:32 UTC
Labels: enhancement
