### ISSUE TITLE
Simpleclans broken with placeholderapi 2.10.7

### ISSUE THREAD

**Issue by Korinocho** [RoinujNosde/SimpleClans#24] opened 2020-07-30 08:44 UTC
WIth the update of PlaceholderAPI to 2.10.7, simpleclans wont start with a placeholderapi method error.

> [05:29:16 ERROR]: Error occurred while enabling SimpleClans v2.12.2 (Is it up to date?)
java.lang.NoSuchMethodError: me.clip.placeholderapi.PlaceholderAPI.registerPlaceholderHook(Ljava/lang/String;Lme/clip/placeholderapi/PlaceholderHook;)Z
        at net.sacredlabyrinth.phaed.simpleclans.managers.PlaceholdersManager.setupPlaceholderAPI(PlaceholdersManager.java:59) ~[?:?]
        at net.sacredlabyrinth.phaed.simpleclans.managers.PlaceholdersManager.<init>(PlaceholdersManager.java:49) ~[?:?]
        at net.sacredlabyrinth.phaed.simpleclans.SimpleClans.hookIntoPAPI(SimpleClans.java:147) ~[?:?]
        at net.sacredlabyrinth.phaed.simpleclans.SimpleClans.onEnable(SimpleClans.java:140) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.1.jar:git-Paper-121]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.1.jar:git-Paper-121]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.1.jar:git-Paper-121]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:500) ~[patched_1.16.1.jar:git-Paper-121]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:414) ~[patched_1.16.1.jar:git-Paper-121]
        at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:471) ~[patched_1.16.1.jar:git-Paper-121]
        at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.1.jar:git-Paper-121]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:940) ~[patched_1.16.1.jar:git-Paper-121]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-121]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]

Thanks!

**Comment by RoinujNosde** [comment] 2020-07-30 10:06
Duplicate of marcelo-mason/SimpleClans#639

Thanks for reporting!
This was fixed on the dev branch and it will be released on the next update. Until then use the previous version of PAPI.

**Closed as completed by RoinujNosde** 2020-07-30 10:06 UTC
Labels: bug

**Comment by Korinocho** [comment] 2020-07-30 12:11
Oh Sorry!
Thanks!
